name: slime Pull Request Check
on:
  pull_request:
    paths:
      - 'slime/**'
  push:
    paths:
      - 'slime/**'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Build
      run: cd slime && go build -v ./...
    - name: Test
      run: cd slime && go test -v -gcflags=all=-l ./...
   